language: csharp
solution: EDDiscovery.sln
mono:
  - latest
install:
  - nuget restore EDDiscovery.sln
  - nuget install NUnit.ConsoleRunner -Version 3.10.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release EDDiscovery.sln /p:DefineConstants=NO_SYSTEM_SPEECH
  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./EDDiscoveryTests/bin/Release/net461/EDDiscoveryTests.dll
