version: 10.6.0.{build}
image: Visual Studio 2017
configuration: Release
install:
  - git submodule update --init
before_build:
  - nuget restore
build:
  project: EDDiscovery.sln
test_script:
  - nunit3-console EDDiscoveryTests\bin\Release\net461\EDDiscoveryTests.dll --result=myresults.xml;format=AppVeyor
after_build:
  - cmd: copy EDDiscovery\bin\Release\net461\EDDiscovery.Portable.zip EDDiscovery.Portable.zip
artifacts:
  - path: EDDiscovery.Portable.zip
cache:
  - packages -> **\packages.config
